version: "3.4"
services:
#Postgres container with env variables
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_DB: graphspace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/PostgreSQL/data
      - ./db.sh:/docker-entrypoint-initdb.d/create_extensions.sh

#Elasticsearch Container
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/var/lib/elasticsearch/data

#Graphspace Image with enviornment variables 
  graphspace:
    restart: always
    image: maheshkasbe/graphspace:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: graphspace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    stdin_open: true # docker run -i
    tty: true # docker run -t
    # build:
    #   context: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate --settings=graphspace.settings.local && 
            python manage.py runserver 0.0.0.0:8000 --settings=graphspace.settings.local"
    depends_on:
      - db
      - elasticsearch

volumes:
  pgdata:
  esdata: